languageCode = "en-us"
title = "Lucas A. Nell"
theme = "kube"
description = ""
Paginate = 1
[Params]
  RSSLink = ""
  author = "Lucas A. Nell"
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""
relativeurls = true
baseURL = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
googleAnalytics = "UA-49535058-2"

[[menu.main]]
    name = "CV"
    weight = 999
    url = "/pdf/Nell_CV.pdf"
