languageCode = "en-us"
title = "Lucas A. Nell"
theme = "kube"
description = ""
Paginate = 1
[Params]
  RSSLink = ""
  author = "Lucas A. Nell"
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""
  disablePathToLower = true # Do not make the url/path to lowercase
relativeurls = true
baseURL = "www.lucasnell.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
googleAnalytics = "UA-49535058-2"




[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

