languageCode = "en-us"
title = "Lucas A. Nell"
theme = "kube"
description = ""
[pagination]
  pagerSize = 1
[Params]
  author = "Lucas A. Nell"
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = ""
  disablePathToLower = true # Do not make the url/path to lowercase
relativeurls = true
baseURL = "www.lucasnell.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
googleAnalytics = "G-LHBZJSJZ5Z"




[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[markup.goldmark.renderer]
  unsafe= true

