---
date: 2017-05-09T17:01:11-05:00
title: "Prospective Students"
menu: "main"
weight: 6
url: "/prospective_students/"
---

I am particularly interested in attracting graduate students who want to combine empirical and theoretical approaches to ecological studies. My lab is diverse, with students having worked on malaria in lizards, biological control of pea aphids, the dynamics of freshwater phytoplankton, fish community composition, plant-pollinator mutualisms, tropical frogs, and other topics. A broad background and interest in collaborating on a wide range of ecological questions is essential.

When I was applying for graduate school, the most important thing I looked for was a place where I had the flexibility and resources to do my own research. Now as a faculty advisor, I encourage students to develop their own projects and interests. There are limits, however, as I don't want to take on students who are so far a field that I can't give adequate advice and support. But the mix of people in the lab provides a rich collective knowledge that can help with a variety of projects. I actively encourage collaborations within the lab, and between lab members and others on campus. To select prospective graduate students to fit in with the collaborative atmosphere of the lab, the entire lab has a strong say in accepting graduate students.