---
title: "Can trait coevolution among competitors promote coexistence?"
description: ""
date: 2017-05-09T17:00:28-05:00
weight: 999
image: "/img/theory-invader.svg"
caption: "Residents invested in exclusion-promoting traits (\"excluding residents\") are more susceptible to exclusion by a new invader because they suppress other species leading to their own evolutionary disarmament"
---


Coevolution among competitors can result in traits that promote 
niche partitioning and coexistence or traits that promote
greater conflict and competitive exclusion.
We used an eco-evolutionary model where competitors "invest" in coexistence- and 
exclusion-promoting traits to assess when trait coevolution
should promote coexistence or exclusion.
We found that communities should often contain both types of traits, but
exclusion-promoting traits should more strongly influence trait 
coevolution community-wide.
We also found that, despite being more influential, species invested relatively
more in exclusion-promoting traits should be most vulnerable to exclusion by a
new invader.
This may make communities containing multiple species with exclusion-promoting
traits transitory
(Nell et al. in revision; [preprint](https://doi.org/10.1101/2022.11.01.514799)).



